/*

  Mock Data has many objects of these fields:
   - Author
   - Title
   - Category
   - Major
   - Professor
   - University
   - Abstract Number

*/


export const mockData = [{ author: 'Elijah Smith',
    professor: 'Olivia Lewis',
    school: 'UMaine Machias',
    major: 'Physics',
    title: 'Machine Learning Approaches to Financial Fraud Detection',
    category: 'Social Sciences and Humanities',
    keywords: ['Machine Learning', 'Financial Fraud', 'Detection'],
    abstract: 'This research explores the application of machine learning techniques in detecting financial fraud. By analyzing large datasets, we developed algorithms that can identify patterns indicative of fraudulent activities. Our findings demonstrate the effectiveness of these approaches in enhancing fraud detection systems, potentially saving millions in losses.',
    abstractNumber: 38893888,
    allAuthors: ['Elijah Smith', 'Olivia Lewis']},
  { author: 'Sophia Campbell',
    professor: 'Mia Lee',
    school: 'UMaine Machias',
    major: 'Political Science',
    title: 'The Psychology of Decision-Making in Uncertain Environments',
    category: 'Social Sciences and Humanities',
    abstractNumber: 75957852 },
  { author: 'Lucy Martinez',
    professor: 'Carter Martinez',
    school: 'UMaine Machias',
    major: 'Business Administration',
    title: 'The Sociology of Online Communities in the Digital Age',
    category: 'Natural Sciences',
    abstractNumber: 48203955 },
  { author: 'Zoe Jackson',
    professor: 'Layla Perez',
    school: 'UMaine Machias',
    major: 'Psychology',
    title: 'Advancements in Human-Robot Interaction for Assistive Technologies',
    category: 'Physical and Mathematical Sciences',
    abstractNumber: 64568884 },
  { author: 'Noah King',
    professor: 'William Smith',
    school: 'UMaine Machias',
    major: 'Political Science',
    title: 'Blockchain Technology in Supply Chain Transparency',
    category: 'Biomedical Sciences',
    abstractNumber: 40679302 },
  { author: 'Joseph Baker',
    professor: 'Aria Thompson',
    school: 'UMaine Orono',
    major: 'Mathematics',
    title: 'Advancements in Human-Robot Interaction for Assistive Technologies',
    category: 'Interdisciplinary Research (research across 3 or more different departments or colleges)',
    abstractNumber: 37625940 },
  { author: 'Ava Rodriguez',
    professor: 'Victoria Thomas',
    school: 'UMaine Machias',
    major: 'Physics',
    title: 'Climate Change and Its Effects on Global Food Security',
    category: 'Physical and Mathematical Sciences',
    abstractNumber: 35716422 },
  { author: 'Henry Adams',
    professor: 'Lucy Miller',
    school: 'UMaine Machias',
    major: 'Psychology',
    title: 'The Psychology of Decision-Making in Uncertain Environments',
    category: 'Business',
    abstractNumber: 82413071 },
  { author: 'Mason Hernandez',
    professor: 'Aiden Perez',
    school: 'UMaine Orono',
    major: 'Business Administration',
    title: 'Machine Learning Approaches to Financial Fraud Detection',
    category: 'Arts',
    abstractNumber: 27882383 },
  { author: 'Emma Taylor',
    professor: 'Ethan Hernandez',
    school: 'UMaine Orono',
    major: 'Biology',
    title: 'Machine Learning Approaches to Financial Fraud Detection',
    category: 'Business',
    abstractNumber: 92969314 },
  { author: 'Aurora Martinez',
    professor: 'William Anderson',
    school: 'UMaine Machias',
    major: 'Computer Science',
    title: 'The Role of Citizen Science in Biodiversity Conservation',
    category: 'Business',
    abstractNumber: 29718536 },
  { author: 'Lucas Robinson',
    professor: 'Scarlett King',
    school: 'UMaine Orono',
    major: 'Psychology',
    title: 'The Role of Citizen Science in Biodiversity Conservation',
    category: 'Natural Sciences',
    abstractNumber: 1457768 },
  { author: 'Chloe Adams',
    professor: 'Liam Rodriguez',
    school: 'UMaine Orono',
    major: 'Physics',
    title: 'Blockchain Technology in Supply Chain Transparency',
    category: 'Business',
    abstractNumber: 14148682 },
  { author: 'Layla Young',
    professor: 'Alexander Roberts',
    school: 'UMaine Orono',
    major: 'Biology',
    title: 'Exploring the Feasibility of Space-Based Solar Power',
    category: 'Engineering and Information Sciences (including Biomedical Engineering)',
    abstractNumber: 60454722 },
  { author: 'Alexander Hall',
    professor: 'Aria Clark',
    school: 'UMaine Machias',
    major: 'Business Administration',
    title: 'Social Media Influence on Adolescent Mental Health',
    category: 'Education',
    abstractNumber: 41498009 },
  { author: 'Zoe Young',
    professor: 'Amelia Jackson',
    school: 'UMaine Orono',
    major: 'Physics',
    title: 'Analyzing the Impact of Microplastics on Marine Ecosystems',
    category: 'Engineering and Information Sciences (including Biomedical Engineering)',
    abstractNumber: 23333306 },
  { author: 'Mason Clark',
    professor: 'Scarlett Hernandez',
    school: 'UMaine Machias',
    major: 'Nursing',
    title: 'Cultural Impacts on Language Evolution',
    category: 'Physical and Mathematical Sciences',
    abstractNumber: 97656877 },
  { author: 'Henry Hall',
    professor: 'Ella Garcia',
    school: 'UMaine Machias',
    major: 'Mechanical Engineering',
    title: 'Social Media Influence on Adolescent Mental Health',
    category: 'Interdisciplinary Research (research across 3 or more different departments or colleges)',
    abstractNumber: 91417686 },
  { author: 'Samuel Scott',
    professor: 'Evelyn Green',
    school: 'UMaine Machias',
    major: 'Mathematics',
    title: 'Advancements in Human-Robot Interaction for Assistive Technologies',
    category: 'Allied Health',
    abstractNumber: 4887031 },
  { author: 'Grace Nelson',
    professor: 'Aria Scott',
    school: 'UMaine Machias',
    major: 'Nursing',
    title: 'Advancements in Human-Robot Interaction for Assistive Technologies',
    category: 'Physical and Mathematical Sciences',
    abstractNumber: 36475226 },
  { author: 'Scarlett Hernandez',
    professor: 'Matthew Wright',
    school: 'UMaine Machias',
    major: 'Mechanical Engineering',
    title: 'Machine Learning Approaches to Financial Fraud Detection',
    category: 'Arts',
    abstractNumber: 29014475 },
  { author: 'Maya Hernandez',
    professor: 'William Green',
    school: 'UMaine Machias',
    major: 'Physics',
    title: 'The Future of CRISPR in Gene Therapy',
    category: 'Physical and Mathematical Sciences',
    abstractNumber: 44667664 },
  { author: 'Elijah Rivera',
    professor: 'Harper Martinez',
    school: 'UMaine Orono',
    major: 'Computer Science',
    title: 'Analyzing the Impact of Microplastics on Marine Ecosystems',
    category: 'Social Sciences and Humanities',
    abstractNumber: 21709418 },
  { author: 'Liam Taylor',
    professor: 'Ella Walker',
    school: 'UMaine Machias',
    major: 'Political Science',
    title: 'Social Media Influence on Adolescent Mental Health',
    category: 'Physical and Mathematical Sciences',
    abstractNumber: 45822327 },
  { author: 'Mia Robinson',
    professor: 'Noah Green',
    school: 'UMaine Orono',
    major: 'Mathematics',
    title: 'The Impact of Remote Work on Organizational Productivity',
    category: 'Physical and Mathematical Sciences',
    abstractNumber: 75710656 },
  { author: 'Evelyn Rodriguez',
    professor: 'Lucas Moore',
    school: 'UMaine Orono',
    major: 'Physics',
    title: 'Deep Learning for Medical Image Analysis',
    category: 'Allied Health',
    abstractNumber: 39877467 },
  { author: 'Zoe Brown',
    professor: 'Scarlett Thompson',
    school: 'UMaine Orono',
    major: 'Physics',
    title: 'Cultural Impacts on Language Evolution',
    category: 'Biomedical Sciences',
    abstractNumber: 74596190 },
  { author: 'Sophie Thomas',
    professor: 'David Rodriguez',
    school: 'UMaine Machias',
    major: 'Mechanical Engineering',
    title: 'Advancements in Human-Robot Interaction for Assistive Technologies',
    category: 'Physical and Mathematical Sciences',
    abstractNumber: 30556122 },
  { author: 'Maya Mitchell',
    professor: 'Aiden White',
    school: 'UMaine Orono',
    major: 'Nursing',
    title: 'Advancements in Human-Robot Interaction for Assistive Technologies',
    category: 'Arts',
    abstractNumber: 75180428 },
  { author: 'Jack Anderson',
    professor: 'Harper Rodriguez',
    school: 'UMaine Orono',
    major: 'Physics',
    title: 'Analyzing the Impact of Microplastics on Marine Ecosystems',
    category: 'Natural Sciences',
    abstractNumber: 82398661 },
    { author: 'Harper Rodriguez',
      professor: 'Harper Rodriguez',
      school: 'UMaine Orono',
      major: 'Physics',
      title: 'Analyzing the Impact of Microplastics on Marine Ecosystems',
      category: 'Natural Sciences',
      abstractNumber: 82398661 }]


  export default mockData;