name: Google App Script - Deployment

on:
    push:
        branches:
            - main

jobs:
  Deploy-Apps-Script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PNPM Package Manager
        uses: pnpm/action-setup@v2
        with:
            version: 10.5.2
            run_install: false
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: pnpm install
        working-directory: GAS/
      - name: Decrypt .clasprc.json (GAS credentials)
        run: |
          gpg \
            --quiet --batch --yes --decrypt --passphrase="${{ secrets.CLASP_SECRET }}" \
            --output $HOME/.clasprc.json .clasprc.json.gpg
        working-directory: GAS/
      - name: Deploy to Google App Script
        run: npm run deploy
        working-directory: GAS/